"""empty message

Revision ID: 1a9098d80e8e
Revises: c2b12586ed32
Create Date: 2020-04-03 19:29:39.358477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9098d80e8e'
down_revision = 'c2b12586ed32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'person', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'password')
    # ### end Alembic commands ###
